name = "gladvent"
version = "0.6.1"
repository = { type = "github", user = "TanklesXL", repo = "gladvent" }
description = "An Advent Of Code runner for gleam"
licences = ["Apache-2.0"]
internal_modules = ["gladvent/internal/*", "aoc_*"]
gleam = "~> 0.34 or ~> 1.0"

[dependencies]
gleam_stdlib = "~> 0.34 or ~> 1.0"
gleam_otp = "~> 0.4"
gleam_erlang = "~> 0.7"
snag = "~> 0.2"
glint = " ~> 0.16.0-rc1"
simplifile = "~> 0.3"
argv = "~> 1.0"

[dev-dependencies]
gleeunit = "~> 1.0"
