name = "gladvent"
version = "0.1.3"
repository = { type = "github", user = "TanklesXL", repo = "gladvent" }
description = "An Advent Of Code runner for gleam"
licences = ["Apache-2.0"]

[dependencies]
gleam_stdlib = "~> 0.19"
gleam_otp = "~> 0.3"
gleam_erlang = "~> 0.7"
snag = "~> 0.2"
glint = "~> 0.6"

[dev-dependencies]
gleeunit = "~> 0.6"
