name: main

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        erlang: ["24.2"]
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/test
        with:
          erlang-version: ${{ matrix.erlang }}
