name: GH and Hex.pm Release

on:
  push:
    tags:
      - v*.*.*
jobs:
  test:
    uses: ./.github/workflows/test.yml

  release:
    needs:
      - test
    uses: TanklesXL/gleam_actions/.github/workflows/release.yaml@main
    secrets: inherit
    with:
      hexpm_user: ${{ secrets.HEXPM_USER }}
      hexpm_pass: ${{ secrets.HEXPM_PASS }}
