name: test

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.0.0
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "24"
          gleam-version: "0.17"
      - run: rebar3 install_deps
      - run: rebar3 eunit
      - run: gleam format --check src test
